name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[http]  # Important: Use [http] for DagsHub

      - name: Configure DVC Remote for DagsHub
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user $DAGSHUB_USERNAME
          dvc remote modify origin password $DAGSHUB_TOKEN
          dvc remote default origin
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: DVC Pull from DagsHub
        run: dvc pull

      - name: Run DVC Pipeline
        run: |
          export MLFLOW_TRACKING_URI=https://dagshub.com/mepaluttam/youtube-comment-analysis.mlflow
          dvc repro
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
